### ISSUE TITLE
TODO for Initial Alpha 1

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/vscode-wpilib#27]
- [ ] Finalize and publish C++ Gradle extension for publishing VS Code include paths
- [ ] Fix C++ examples and templates to work with the 2018 libraries
- [ ] Disable Desktop testing and Simulation
- [ ] Wait for vscode-cpp 0.17.6 (Should be today, 6/28 sometime)

**Comment by ThadHouse** [comment]
Done
